source 'https://rubygems.org'



gem 'haml', '~> 4.0', '>= 4.0.7'
gem 'cowsay'
gem 'simple_form', '~> 3.2', '>= 3.2.1'
gem 'paperclip', '~> 4.3', '>= 4.3.6'
gem 'carrierwave', '~> 0.11.2'
gem 'rmagick', '~> 2.15', '>= 2.15.4'
gem 'better_errors', '~> 2.1', '>= 2.1.1'
gem 'friendly_id', '~> 5.1'
gem 'awesome_print', '~> 1.7'
gem 'pry-awesome_print', '~> 9.6', '>= 9.6.10'
gem 'geocoder', '~> 1.3', '>= 1.3.7'
gem 'rails-api', '~> 0.4.0'
gem 'nokogiri', '~> 1.6', '>= 1.6.8'
gem 'cane', '~> 3.0'
gem 'rake', '~> 11.2'
gem 'masonry-rails', '~> 0.2.4'
gem 'act_as_importable', '~> 0.0.11'
gem 'cloudinary', '~> 1.1', '>= 1.1.7'
gem 'shoulda', '~> 3.5'
gem 'factory_girl', '~> 4.7'
gem 'simple_hashtag', '~> 0.1.9'
gem 'devise', '~> 4.1', '>= 4.1.1'
gem 'erd', '~> 0.4.0'
gem 'bootstrap-sass', '~> 3.3', '>= 3.3.6'
gem 'cocoon', '~> 1.2', '>= 1.2.9'
gem 'bundler', '~> 1.12', '>= 1.12.5'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.15'
gem 'rails_12factor', group: :production
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

gem 'puma'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
